### ISSUE TITLE
字下面的空間過多，請問有沒有方法改善呢？

### ISSUE THREAD

**Issue by iamsonychan** [chiron-fonts/chiron-hei-hk#10]
![IMG_2637](https://user-images.githubusercontent.com/127072849/223016831-85285c81-7863-46fe-a793-19326bc2386c.JPG)
紅色括號的空間過大，在AI很難對齊其他東西，之前chiron sans也沒有那麼大（chiron hei超大！），請問有方法可以解決嗎？謝謝你。

**Comment by tamcy** [comment]
你好！這問題是因為 Adobe Illustrator 曾經有一個 bug，就是用字體內最高的字圖作為文字物件選框的高度。
本字體繼承自思源黑/宋體，思源有好些字圖 (U+3031, U+3032 及 U+2E3A, U+2E3B 的直式) 的高度是一般中文字形字圖的兩至三倍，結果 AI 就用了這些字高作為選框高度。

我在 Chiron Sans 曾嘗試透過移除相關字圖和竄改字體寬高資料來繞過問題。但在 Chiron Hei 選擇不再做這些處理，因為
1. 其中一個兩倍高度字圖是作為中文破折號的直式（中文版破折號 U+2E3A 橫式佔兩個字寬，直式佔兩個字高）。移除了這個字圖，若將使用了這個字符，橫排改作直排時，這字符便會變成空格，這點絕不理想。
2. 竄改字體寬高資料會令字型檔違反字體規格，也會令軟件在顯示這些字元時出現異常。
3. 據知相關問題在新版 Illustrator 已經修正。

新版昭源黑體希望能提倡這類字符的使用，不欲為一個舊版軟件的問題破壞字體完整性，所以最終決定不作修改。造成不便只好說聲抱歉。

相關問題參考：https://github.com/adobe-fonts/source-han-sans/issues/186
