### ISSUE TITLE
䯢 没改麻部件

### ISSUE THREAD

**Issue by NightFurySL2001** [chiron-fonts/chiron-hei-hk#11]
![image](https://user-images.githubusercontent.com/33471049/230297122-d8706682-96b4-46c6-bb30-3395f07154f2.png)

**Comment by tamcy** [comment]
Updated in 2.508.

按䯢非 Big5/HKSCS 字，亦非常用字，網站有說明：「至於 Big-5/HKSCS-2016 字表之外的中文字，並不屬於昭源字體的正式支援範圍。即使有重新映射或重繪等動作，最終字樣也不保證盡皆符合本字體所選定的筆形原則。換言之，假如該字碼不屬思源字體的支援範圍，輸出字樣不符本字體屬意式樣並不能算作 bug，使用時敬請留意。」而麻部件字在 2.502 改為從「𣏟」，故先處理常用字。
