### ISSUE TITLE
新增商業使用案例

### ISSUE THREAD

**Issue by CaiMiao** [chiron-fonts/chiron-hei-hk#15]
（為保持版面整潔，提交完畢即close）
@tamcy 朋友你好，好多謝你嘅辛苦付出。
我自己都係廣東人，所以今次用廣東話send俾你。

我哋有一間遊戲在地化工作室，在選定字型期間瞭解到你呢隻project。
我個人都比較認同「字形中立」嘅諗法，於是決定將Chiron Hei HK/Chiron Song HK作為最近一部作品的繁體中文基礎黑體/宋體字型。
喺下面呢條link可以睇到我哋嘅嗰隻game。
https://ec.nintendo.com/HK/zh/titles/70010000077561
（Download到遊戲主機後可以在系統選單「智慧財產權資訊」睇到License標示）

順便想問下，將來有無機會喺project專頁新設商業使用案例欄目，刊登有關案例資訊？（譬如我哋依家呢隻）
（冇計劃都冇問題，只喺問下）

**Comment by CaiMiao** [comment]
Close as intended

**Comment by tamcy** [comment]
你好。首先好高興昭源字體於你有用，謹祝成功！
可惜我冇 Switch，應該話我冇打機好耐，不過都會試下有冇辦法親身一看。

至於使用案例頁，其實我之前喺電視、書局、網上都偶然會見到零星昭源字體使用實例，曾經諗過是否可以介紹，但思前想後，「使用案例頁」會牽涉頗多問題，例如我諗過：
1. 若得零星例子觀感不佳不如唔做。
2. 引用材料禮貌上應先徵詢對方同意，需時間人力；
3. 如果先斬後奏，一旦對方要求撤回唔係咁好睇；
4. 可能會遇上有時某產品唔想同某產品擺埋一齊（例如嫌對方格調低），如何解決紛爭？
5. 作為一開源專案，點解只介紹「商業案例」，係咪應該擴展至「任何案例」？即是要更多時間處理；
6. 用本字體做 webfont 網站，又是否應該收錄？
等等。所以，字體作為一「興趣專案」，自知目前難以投放適當時間處理下，此事決定按兵不動，請見諒。
不過，我非常歡迎好似閣下咁向我告知用例 🙂。
