### ISSUE TITLE
澳門的街名罕見字 (2348D)

### ISSUE THREAD

**Issue by du3357** [chiron-fonts/chiron-hei-hk#16]
非常欣賞昭源黑體，解決了澳門的街名"扊扅巷"的寫法，使"扊扅"兩字的上半部"戶"字的字型一致。
另，澳門路環有一街道名為"紅(木何)路"，其中(木何)是罕見字，只見於佛經，意思同荷，與杧芒、槤蓮的原理相同。(木何)字的Unicode為2348D，因未被列入HKSCS而缺少字體輸出上的支援。希望可考慮將(木何)字納入昭源黑體，謝謝。
![Rua das Schimas](https://github.com/chiron-fonts/chiron-hei-hk/assets/173599628/f4fa9e8d-9684-4e12-bbc0-c83362f8d510)

**Comment by tamcy** [comment]
你好，已在最新版本 (黑體: v2.511, 宋體: 1.012) 加入此字。
![image](https://github.com/chiron-fonts/chiron-hei-hk/assets/959433/f49d6612-2e26-483d-8a72-379d5aaceee3)
