### ISSUE TITLE
Webfont 受CSS佈局影響渲染

### ISSUE THREAD

**Issue by efast1568** [chiron-fonts/chiron-hei-hk#17]
Hi,Sir

首先，謝謝這個字型，我很喜歡"字面調整軸"及符號字元的處理方式，簡/繁一體，版面又非常令人舒服。

有個webfont顯示的問題想跟您請教一下看法。

Chiron Hei HK WS 使用時，在一些CSS佈建下，如position: sticky，win系統下，會影響部分的字型渲染(請原諒我不確定是否這樣表達)
PS. 版面中的全部字元，使用同樣設置 / 在Firefox下沒有這種現象，或許運算機制不同

![螢幕擷取畫面 2024-07-12 084119](https://github.com/user-attachments/assets/82a3fd24-61b8-48a6-a643-ddf6f9e20a11)

在[昭源字體](https://chiron-fonts.github.io/)的主頁，右側的章節區塊，也有這種現象，字型邊緣會有比較明顯的"齒狀"

![螢幕擷取畫面 2024-07-12 085535](https://github.com/user-attachments/assets/e6e37dfa-d4de-4105-9382-3af6cd34ff86)

可以在這些區塊加大字重，會改善，但又感覺粗細不協調。

在Noto Sans TC下，雖然也看的出字型受到影響，有些微變化，但邊緣線條還算清楚完整

![螢幕擷取畫面 2024-07-12 084100](https://github.com/user-attachments/assets/f13a2ec4-0390-4780-aef9-daa6c865f030)

不知您這邊是否有相關經驗能提供我改善這種現象。

感謝，日安！

**Comment by tamcy** [comment]
很高興你喜歡這款字體 😊

經測試，在説明網站 position: fixed 的區域，字體的反鋸齒(AA)模式會由 subpixel 變成 grayscale, 這似乎就是你所説的「邊緣齒狀」成因：
![Untitled](https://github.com/user-attachments/assets/2cccd6a9-e4b5-4a9e-83e5-68be610fa12d)
（Chrome，左—有 position: fixed；右—移除 position: fixed 之後）

我懷疑這個不一致在 1080p 或以下的解析度較明顯。我使用 1440p 熒幕，其實完全沒有察覺 AA 模式不一樣。

另外，這個情況其實在 Firefox 也有，只是可能因為 Firefox 本身字體渲染調得較濃，才不致察覺：
![firefox](https://github.com/user-attachments/assets/9f0526f5-155a-4e99-9613-d3a200dff3c9)

還有，`position: fixed` 不是令反鋸齒模式改變的充分條件。因為我做了一個簡單 html 再啟用 `position: fixed`，AA 仍然是 subpixel。看來還有一些 layouting 因素促成這一變化，但暫未能肯定是甚麼。

本來我以為這只是 Blink 引擎問題，還想到 Chromium 回報；事實卻是 Firefox 也有出現相同情況，那就令人懷疑會不會是 Windows Cleartype 引擎的事。

所以抱歉沒有甚麼有用建議，只是將目前發現寫下來。

**Comment by efast1568** [comment]
> 所以抱歉沒有甚麼有用建議，只是將目前發現寫下來。

謝謝抽空排查，這樣的現象讓昭源在Dark mode的搭配上有點吃虧
看起來會有點不太舒服的虛無感

謝謝你同步重現了問題點，我相信總有一天能明白
字型是門學問，繁體尤其小眾，希望它愈來愈好！

**Comment by tamcy** [comment]
更新：至於報告所說的，Noto Sans TC 上的不同情況，經了解原因是 Google Fonts 上的 Noto Sans 系列字型是從 TTF 版本轉換而成，字圖以 TrueType (quadratic B-splines) 外框儲存，至於昭源是以 OTF 版本轉成，所以字圖以本身的 Postscript/OpenType (bicubic B-splines) 外框儲存（WOFF2 是容器，兩種外框都支援）。而瀏覽器/作業系統對 TrueType、OpenType 兩種格式的處理、渲染方式會有差異 (我在 #3 也有談過)。我做了一個測試頁：

https://tamcy.github.io/chrome-subpixel-grayscale-aa-difference/ (OpenType 外框)
![image](https://github.com/user-attachments/assets/b004d4ea-2649-4977-b456-0c38202f6197)

https://tamcy.github.io/chrome-subpixel-grayscale-aa-difference/index-ttf.html (TrueType 外框)
![image](https://github.com/user-attachments/assets/2e6743b6-d195-4ec7-870e-c6c7a981537b)

同樣是 250 字重，在黑底白字場合，TTF 外框比 OTF 外框清晰。外框只是格式不同，所以問題應該出在渲染引擎。
我已經將這個問題回報，只是不知道 Chrome 那邊會不會、何時處理。我也打算在下一版本多提供一 TTF 外框的網頁字型，讓用家按需要選用。

**Comment by efast1568** [comment]
> 我已經將這個問題回報，只是不知道 Chrome 那邊會不會、何時處理。我也打算在下一版本多提供一 TTF 外框的網頁字型，讓用家按需要選用

是的，我的網站在　”chiron-hei-hk-webfont-truetype@0.0.1”　上獲得了很好的顯示效果
困擾已久的問題終於有解了，期待！

**Comment by tamcy** [comment]
有相同問題的朋友可試用新版 v2.514 的 Truetype webfont 格式。
由於沒有其他本字體可做的地方，故 close issue。
順帶一提，這個問題（opentype 與 truetype 渲染效果差異）在 Linux 和 Mac 都沒有出現。
