### ISSUE TITLE
“彔”部件

### ISSUE THREAD

**Issue by garfieldLSY** [chiron-fonts/chiron-hei-hk#18]
請問“彔”末筆作點好還是捺好？

**Comment by Scratchbin** [comment]
捺，按旧字形惯例

**Comment by tamcy** [comment]
首先「彔」「隶」部件處理手法相似，下面談的也是沒有避讓的情況。
黑體而言，新字形大多跟從手寫習慣作四點，看起來也順眼。
宋體新字形商業產品末筆似乎仍作捺筆居多，可能是宋體比黑體更難處理四點和上下的輕重平衡。
昭源先做黑體，再做宋體，不想二者偏差太多，所以選擇了四點。
在宋體「彔」還好；「隶」盯着看倒真的沒有捺筆般習慣。
本字體採用四點主要是黑體先推出，製作宋體選擇筆形時不想與黑體相差太遠。
個人喜好吧。

**Comment by Scratchbin** [comment]
> 捺，按旧字形惯例

看串仓库了，草

**Comment by NightFurySL2001** [comment]
如果要求分开，那么Big5的「筄」字可能可以参考v1 JP 的分离款式。目前昭源使用的是 TW 修改竹头。
![image](https://github.com/user-attachments/assets/6288718f-113f-4c4e-9df0-72a55adb0391)

**Comment by garfieldLSY** [comment]
再考慮一下罷，能不能宋體和黑體字全作捺筆？
