### ISSUE TITLE
Inclusion into Google Fonts

### ISSUE THREAD

**Issue by hfhchan** [chiron-fonts/chiron-hei-hk#2]
我見到近排閂咗 Chiron Sans 加入 Google Fonts 嗰個 issue
我見到而家加字體嗰個流程 update 咗，參考 https://github.com/google/fonts/issues/4377
佢哋本身 fast track 嗰啲仲係 autobuild 嘅，參考 https://github.com/googlefonts/morisawa-biz-ud-gothic/
有冇考慮再加過？

**Comment by tamcy** [comment]
多謝提供資料。唔敢話完全唔會再考慮 submit，只係
* 之前我想款字收入 Google Fonts 最大原因係想有個唔使 self-hosting 嘅 option。而家可以用 jsDelivr CDN，呢方面未必再須倚靠 Google Fonts。
* 我覺得呢款字嘅賣點（如有）之一係 variable format WOFF2，但 Google Fonts 呢一刻仲未有完整 support（就算款字係 VF 都只能載入 static instance）。
* WOFF Subsetting 範圍不同，可能會造成混淆。

仲未提 set up repo, building pipeline 之類嘅改動，所以目前興趣確實不大。如果搞一大輪佢先話唔受理就盞嘥時間。所以，假如我真係好得閒，都會睇下佢篇 https://googlefonts.github.io/gf-docs/Spec/ 點寫，然後又睇下配唔配合到，但呢啲都唔係短期內發生嘅事了。

**Comment by hfhchan** [comment]
雖然我覺得上咗 Google Fonts 會多好多人用，可以俾到更多大公司都用到，不過又要改 pipeline 又少好多特點，的確都幾多缺點。

Btw 如果想做，我估最簡單係將你呢個 repo 嘅 build product decompile 做 ufo, 然後 clone 佢個 example repo, set up 返個 pipeline. 噉樣就唔使改晒用佢啲 pipeline.

**Comment by tamcy** [comment]
> Btw 如果想做，我估最簡單係將你呢個 repo 嘅 build product decompile 做 ufo, 然後 clone 佢個 example repo, set up 返個 pipeline. 噉樣就唔使改晒用佢啲 pipeline.

係，呢個都係我嘅初步諗法，即係開多個 repo 專 serve Google Fonts，有新 release 就喺呢個 repo 就扯個 latest version 去 build，Google Fonts 嗰邊好似話 CJK fonts 唔使 build from scratch 用 TTF 都 OK 𠻹，只係唔知 Google Fonts 接唔接受呢種 upstream 方法。

**Comment by hfhchan** [comment]
我問過下話用思源改出嚟嘅考唔考慮，佢哋話主要睇 value add，如果齋改幾個 glyph 就會好 low priority

我記得以前有個表話改咗幾百個，又 remap 咗幾百個，但我揾唔返。以前仲有個 comparison 講 Chiron 系列有咩修正，但係而家個新 site 揾唔返張圖…

話説，而家 Google fonts 有啲 Morisawa 嘅 UD Font，如果可以攞來改繁中版應該幾正（又開坑（

**Comment by tamcy** [comment]
>我記得以前有個表話改咗幾百個，又 remap 咗幾百個，但我揾唔返。

如果你指嘅係網站，之前係有個 counter 嘅 eye-candy 嘢，而家冇嘅原因係我 revamp 個網時想喺 end user 角度嚟睇應該有啲乜嘢內容，而照計 end user 係唔使亦唔應該要首先知道思源係乜至可以明白我款字嘅特徵，所以你會見我喺新網站「技術結節」範圍外都盡量唔提思源字體。而究竟呢款字改咗思源啲乜，其實對 end user 根本唔重要，之前個網提呢樣嘢反而顯得太 technical。

再者，真係對呢啲較為 technical 嘅嘢有興趣嘅用者其實亦可以參考 https://github.com/chiron-fonts/chiron-sung-hk/tree/release/resources 裏面，json file 有 summary，PDF 又有比較，喺 website 特別再提個意義不大，所以冇加。

> 以前仲有個 comparison 講 Chiron 系列有咩修正，但係而家個新 site 揾唔返張圖…

唔知你係講上面個 PDF，定係會改邊一類字？如果係後者應該係指昭源甄黑體 CYanHeiHK 嘅圖片範例，而且幅圖係同台灣版比較，而家都唔再適用。其實新網亦有講個大方向：https://chiron-fonts.github.io/technical-details/motivation/

> 話説，而家 Google fonts 有啲 Morisawa 嘅 UD Font，如果可以攞來改繁中版應該幾正

如果你問我，我去做嘅機會就微乎其微，因為我唔係熱衷於造字嘅人，之所以有昭源字體都係因為自己有用，例如自己工作做 website 不甘於 css 用 system fonts 但又畀唔起錢買商業字體授權，又或要做 PDF 時唔想走版權灰色地帶，但對某啲字嘅呈現方法（寫法）有自己嘅愛好，於是決定自己去做，而唔係因為喜歡造字所以搵啲 project 嚟搞。但暫時自己又未有需要多一款黑體字（至於森澤款字得日文字集呢啲更唔好講）。
