### ISSUE TITLE
疑問：UpstreamDifferences裏面CID的*號

### ISSUE THREAD

**Issue by NightFurySL2001** [chiron-fonts/chiron-hei-hk#20]
部分UpstreamDifferences.pdf裏的新繪字符，CID值有標 * 號，請問是什麽用途？
![image](https://github.com/user-attachments/assets/52fb41eb-3ccb-43a0-8dfb-367a64fb8080)

**Comment by tamcy** [comment]
`*` 號表示 ExtraLight 和 Heavy 之間還有一個 master。
