### ISSUE TITLE
otf版12號大小看起來怪怪的

### ISSUE THREAD

**Issue by ggyy020406** [chiron-fonts/chiron-hei-hk#3]
![CHHKM](https://user-images.githubusercontent.com/15969204/165003822-9c50cf5e-7c8d-4790-903b-20b8fc33271f.png)
hi , 我這張圖左邊是otf右邊是ttf
請問為什麼otf版的12看起來好像怪怪的
系統環境是繁中win10 21H2 64bit

**Comment by tamcy** [comment]
這不是一個容易解答的問題，最簡單的答案就是：原因主要出在作業系統。

較詳細的說明：
1. 昭源字體的 Opentype 格式檔使用了 Postscript 外框，而 TrueType 格式則使用了 TrueType 外框。
2. 之所以有兩種不同外框格式，說到底就是商業競爭下的結果 (OpenType 是 Adobe + Microsoft 的產物，TrueType 是 Apple + Microsoft 的產物)。現在多數作業系統都支援兩種格式則是後話。
3. 無論是哪一種外框格式，均須先作處理才能顯示在點陣電腦熒幕之上，這個過程稱為 Rasterization 柵格化。
4. 不同的外框格式所使用的柵格化引擎是不同的。引擎的運算方法不同，最終的顯示效果可以有很大分別。
5. 從前熒幕尺寸不大，解析度也不高，要在低解析度、小字號下呈現最佳效果，對柵格化引擎來說一個很大的挑戰。在這方面，Opentype 和 TrueType 的採用的策略有很大分別，但由於跟這個 issue 無關也就不多說了。總而言之，兩者或多或少都有依賴一種叫作 hinting （渲染提示）的訊息，這種訊息會嵌入到字體中，來提示柵格化引擎如何將像素「繪畫」到熒幕上。
6. 加入 hinting 訊息方法有兩種：一種是人手加入，逐個字號逐字逐筆去處理，一種是利用軟件自動加上，但精確度當然比不上前者。中日韓字體一般使用後者，因為這類字體收字量大，除非有財有勢者如微軟，否則很難投放龐大資源去做。

昭源字體無論何種格式都沒有配備任何 hinting 訊息。最大的原因是個人認為目前熒幕（包括手機、平板電腦）都是朝向高像素密度的方向走。以閣下的截圖為例，當中的 12 號字應該是在 1920x1080 解析度下的顯示效果，但到了 4K 熒幕，同一號字的寬高比是原來的 200%（想像截圖中 24 號字在遠距離觀賞的效果），這時候 hinting 訊息的作用就不是很大了（Mac 系統更是完全不會理會字體中的 hinting 訊息）。也必須承認我自己日用使用的是 2560x1440 和 3840x2160。而且，由軟件自動加上的 hinting 訊息也不見得可以完滿解決顯示上的缺陷。

所以，講了這麼多，假如你的問題在於為甚麼 TTF 和 OTF 預覽效果不同，答案就是：你所看到的情況是 Windows 的柵格化引擎所造成。TTF 和 OTF 採用的柵格化引擎不同，運算方式不同，實在難以一概而論。

要繼續探討的話，問題可以引伸到：那麼昭源字體要不要加入 hinting 訊息？會不會改善這個情況？這時就要明白，首先人手 hinting 不會考慮，而 auto-hinter 也不是加上了就一勞永逸。請看下圖（Windows 11 21H2、1920x1080）：

![github](https://user-images.githubusercontent.com/959433/165101557-4f9749ef-4a34-4b1f-a449-56e62e29cd01.png)

左邊的是思源黑體 (有 auto hinting)，中間的是昭源黑體（新版，沒有 auto hinting），右邊的是昭源黑體（舊版，有 auto hinting）。在 12 號字，兩款有軟件自動 hinting 訊息的字體，雖然效果不太一樣，但筆畫的確沒有那麼粗。但試看 24 號字的「語」字，中間沒有 hinting 的字樣，兩個橫筆的間距卻更加自然。所以這是個兩難，加了 auto hinting 可能另外一些人會不滿。

而更更麻煩的是，其實在 Windows 的柵格式引擎，有使用兩種 Anti-aliasing 抗鋸齒運算方法。你認為「怪怪的」字樣，可能是採用較新的 DirectWrite、而使用了灰階抗鋸齒出來的效果（更正，Directwrite 也有支援[Cleartype](https://learn.microsoft.com/en-us/windows/win32/directwrite/introducing-directwrite)，但截圖確是用了灰階抗鋸齒），但其實在某些使用 GDI 的應用程式，應該還是會採用 Windows Vista（還是 XP？不是記得太清楚）年代引入、稱作 ClearType 的 subpixel 抗鋸齒技術。這導致同一系統、同一字體、同一字號，在不同的應用程式，出來的效果可以很不一樣——看看附圖，筆畫是沒那麼粗了，但「語」卻無故缺了一橫筆。

最後，順帶一提，在 2013 年，[Adobe 向開源 FreeType 社羣貢獻他們自家的 CFF 柵格化引擎](https://blog.typekit.com/2013/05/01/adobe-contributes-cff-rasterizer-to-freetype/)。約十年後的今天，請看看附圖中 Ubuntu 22.04 的渲染效果。

既然如此，按現時情況，假如你要的是 Windows DirectWrite 在小字號的熒幕顯示效果，我會建議改用 TTF 版。至於是否為昭源字體加回 hinting 資訊，則要再有多一點資料才能作決定。

延伸閱讀：
- https://blog.justfont.com/2017/07/opentype-wars/
- https://www.thetype.com/2016/09/10968/
- https://kanru.info/zh-tw/blog/source-han-sans-and-freetype/

**Comment by ggyy020406** [comment]
很詳細又專業的解答
感恩，又學到了新知識
我的解析度的確是 1920x1080
如果問題一半算是出在解析度太低感覺是不用加回 hinting
1080p早晚會被淘汰
你的處理聽起來是正確的
