### ISSUE TITLE
異體字的處理

### ISSUE THREAD

**Issue by archerindigo** [chiron-fonts/chiron-hei-hk#5]
你好，我留意到一些字在昭源體所採用的寫法不一致，令人有點令我困惑，想問一下作者對於異體字是以什麼準則處理？

例如「於」在昭源體採用了《香港小學習字表》所指的異體字寫法，但這不是學校所教、日常常見，亦非《香港電腦漢字參考字形》的寫法，香港版思源體也是使用正寫，所以不知為何昭源體偏偏反其道而行？

「電」按香港正寫穿頭，「婁」的一豎卻不按正寫用不穿底的寫法，如果按正寫應該兩者皆穿，但後者卻採用不穿底寫法，又有何好處？

艸部（草花頭）在昭源黑體是用中間一長橫的中日韓寫法，在宋體卻是用中間兩短橫的台港澳寫法，這又是有什麼原因？

**Comment by tamcy** [comment]
你好！首先為免誤會，不知先生是否已看過敝網站的[創作背景](https://chiron-fonts.github.io/technical-details/motivation/)頁？

**Comment by archerindigo** [comment]
是有看過的，所以我也是拿著當中示例的字提出作為普通用家感到的疑惑

如果以熟悉為依歸，「亦」的處理我認同，但「於」我想香港人會比較熟悉正寫。

要兼顧顯示效果，艸部在黑體和宋體使用不同寫法會有分別的好處？而「亦」第三筆用捺而非豎，我認同符合以熟悉為依歸的原則，但顯示效果卻沒有那麼對稱，所以這就裡似乎就有衝突。

如果說「婁」穿底會有視覺干擾，「電」穿頭也會啊，不過我自己就不太感受到穿頭/底的視覺干擾。

**Comment by tamcy** [comment]
謝謝回覆。就先生疑問，謹覆如下。

一、首先有關「於」字，必須承認我不知道現時學校所授之書體為何，倒是我在八十年代上中小學時，接觸寫法確是「右上從人」，也未曾因此書體與周遭所見不同而生疑。其時教育署《常用字字形表》已經出版，不過大抵學校教育未有完全遵用，亦似乎不如現時教師般吹毛求疵（如數年前甜字首筆風波）。先生指本字體所採從「右上從人」寫法非日常常見，對我來説反而不可思議。假如先生説的是印刷字形，那麼「右上從人」寫法絕對佔優勢。如果説的是手寫字形，既然連《常用字字形表》也有收入「右上從人」寫法，以之為「通行的異體字」、「可以接納為並行的異體字」，至少當時（八、九十年代）流通程度應該不底；就我所見通行程度也高於標準字形。另外，我又找到[自由香港字型網站有一則六年前由開發人員所寫的貼文指](https://www.collaction.hk/s/freehkfonts/objective/289)：「例如『於』字相信大部份人右上角都採『人』」。

二、草頭宋、黑所採寫法不同。原因在於宋體有橫筆有三角飾筆，在粗字重時極為明顯，使用雙十字寫法效果欠佳，因而用相連版本。而黑體並無此問題，另個人屬意雙十字版本。又有些是基於個人對於宋、黑的感覺所做的選擇，或是礙於某種筆形假如要修改太過費時，覺得不改問題不大所以放着不管。這些差異恕難一一細述。

三、「婁」字説的視覺干擾，指的是在粗體或正文字號下，三筆無可避免會太貼近所造成，而「電」字並無此問題。

![v2](https://user-images.githubusercontent.com/959433/184891339-70e45cdf-6535-45e4-a852-ee4472736bac.png)

所以這並不單在於筆畫貫穿與否。先生不覺有問題，不妨；但在我看來頗覺礙眼。我也留意到蒙納中宋、粗宋體有保留（或改成）穿尾寫法，不過經試驗後最終還是決定選用不穿的版本。

我知道先生未必同意以上所説。這其實也反映了字體設計難免涉及主觀因素。既然本字體希望能提供一套「平衡標準字形和印刷體慣用筆形的現代筆形風格黑體和宋體字型」，而參考對象是《香港電腦漢字參考字形》和「日常生活所見的『事實標準』」（主要是中文字體廠商，尤其香港設計師所設計的字體，如蒙納字體、華康儷字系列），其成品自然會是兩者之間取捨或拉鋸下的結果。任何人都可以商榷為何本字體某某字形選用偏重標準字形而不選用印刷體，或某某字選用印刷體慣用筆形而不選用標準字形。不過，我曾經就字形標準問題請教過一位當年有份參與《常用字字形表》研訂但未有具名的學者。他的回覆大意是：其實電腦字體不遵從《字形表》並無大礙，這好比書法，可以看成是一種藝術形式的表達。你總不會質疑為甚麼一個人所寫的書法，當中某某字不符合教育部門的字形表標準吧？雖然自問所做字體遠遠未及高攀「藝術」之名，不過該位老師所講，確有道理。而我相信這對於本字體在字形上的取捨同樣適用，字體設計固然有些判斷好壞的客觀因素在，但筆形的取捨牽涉主觀感受在所難免。因此，先生或不妨將本字體當成一獨立產品看待，即是直接使用看看是否合自己心意，而不必為某字或某部件為何會遵從或不遵從某標準費心。

**Comment by archerindigo** [comment]
謝謝您的解說，我絕對尊重昭源體作為獨立作品有個人偏好，只是想更清楚了解那些字形選擇背後的原則而已。
我使用思源和昭源的時間尚淺，有些顯示上的觀感問題未必很深刻體會到，或許日後會認同您的觀點。

至於「於」的寫法，的確較多電腦字體會用從人的寫法，不過我讀書時是教一撇一橫的寫法，身邊80後、90後的朋友也是這樣手寫，如果事實標準是建基於一般人常用寫法和參考字形標準，而不是建基於該字在其他印刷字型的使用傾向，我主觀地會選擇一撇一橫作標準。

**Comment by eaganlai** [comment]
純粹補充，八十後以下寫於會用「撇橫」而非「人」，全因教育局。教育局規定後，朗文等教育出版社便依教育局規定印書。八九十後以出版社刊物學習的人，自然以書為準。

附上各種開源字體的寫法︰
![Artboard1](https://user-images.githubusercontent.com/74284983/203342523-2f35df0b-09c5-42fd-8aac-b74e05ffb0bc.png)
