### ISSUE TITLE
嵌入PDF字體時，英數出現亂碼或所有文字被點陣化

### ISSUE THREAD

**Issue by fei0316** [chiron-fonts/chiron-hei-hk#7]
本人對字體方面只是小有研究，如果issue寫得不太清楚敬請見諒！

我在 Windows 10 21H2 和 最新版 Word (Office 365) 中使用 Chiron Hei HK Text OTF 版本時，發現無法匯出嵌入字體的PDF文件。使用 Word 內置的 PDF 匯出工具將變爲點陣化（強制關閉點陣化選項亦然），而使用 Acrobat 匯出時則會在英數字體出現亂碼。效果如下（又上至下爲 Word 原件，Acrobat 匯出效果，Word 匯出效果
![圖片](https://user-images.githubusercontent.com/8295915/197703179-c5fc06ab-77c9-4955-a81a-8f42d4c5c3f1.png)

剛剛進行過簡單測試，發現使用思源宋體 (OTF) 時在 Acrobat 可以正常匯出但 Word 仍然會點陣化，使用更紗黑體 (TTF) 時則兩者都能正常匯出。

更新：剛剛看到這個：[https://answers.microsoft.com/en-us/msoffice/forum/all/word-export-as-pdf-keep-adobe-opentype-fonts-otf/a2d01edd-3e13-4b35-9220-fcd6228d4832](https://answers.microsoft.com/en-us/msoffice/forum/all/word-export-as-pdf-keep-adobe-opentype-fonts-otf/a2d01edd-3e13-4b35-9220-fcd6228d4832)，看來還是直接用TTF版本比較好。

**Comment by tamcy** [comment]
首先謝謝回報問題。

TTF 和 OTF 的問題須分開處理。一如閣下所說，Word 自身的 PDF 匯出功能無法正常支援 OTF 字型檔，其結果不如預期般能保留外框曲線特徵，反而變成點陣字。TTF 字型則無此問題。這是一個已知問題，並不限於本字體。

至於使用 Acrobat 匯出，不知閣下是否指列印至 Adobe PDF 裝置的功能？使用這個工具，真正的 PDF 輸出者是 Adobe Acrobat 軟件，如有問題理論上跟 Word 無關，這也是我關注的重點。遺憾是由於在下並無訂閱 Adobe Acrobat 或包括此服務的方案，所以不能邊試邊調去找出問題所在。而且，由於我試過 PrimoPDF 的列印功能、LibreOffice 的匯出到 PDF 功能和 Chrome 及 Firefox 本身的列印至 PDF 檔案功能都沒有出現問題，要真正找出問題源頭比較困難。

目前猜想，假設 Word 軟件本身沒有問題，那麼字型檔應該只有一個地方會觸發此一情況，閣下如有餘暇，不知能否幫忙一試？

1. 首先，我想知道這個問題是否也同樣出現在昭源宋體 Chiron Sung HK？兩款字體的構建流程完全相同。
2. 若是，我準備了一個新的測試用 OTF 檔案 ([連結](https://github.com/chiron-fonts/chiron-hei-hk-bughunt/raw/main/ChironHeiHK-Text-L.otf)，版本是 0.001))。測試前，請先移除本機上的所有 Chiron Hei HK / Chiron Hei HK Text 字型，然後安裝此單一字型 (測試字型只有 Chiron Hei HK Text L，但其他字重可能造成影響，所以最好先全部移除)，再使用 Word 的列印至 Adobe PDF 功能，看看有關問題是否依然存在。如果問題解決，就是我的猜測正確，我再看看如何修正。
3. 否則，如果問題仍然存在，請再試用 Notepad（記事本）輸入相關文字再列印至 Adobe PDF，看看輸出的 PDF 是否正常。這是希望確認問題跟 Word 本身無關。

謝謝！

**Comment by fei0316** [comment]
謝謝你的回覆。我按照你提供的三個測試方式，用以下的 PDF 產生方式都匯出了一遍：

1. 使用 Microsoft Print to PDF 列印
2. 使用 Adobe PDF 列印
3. 使用 「匯出」中的 Adobe PDF 建立 (Adobe PDF Maker)
4. 使用 Word 「匯出」中的內置的 PDF 建立器
三、四指的分別是下圖的頭兩個選項：
![圖片](https://user-images.githubusercontent.com/8295915/198924058-5d3d1179-e05d-46a9-a86c-e8cf7e884678.png)

結果如下：
### Chiron Sung

1. 全部亂碼，而且檔案超過100MB，懷疑是把整個字體內嵌了（我的測試文件包括了 Chiron Hei, Sung 的所有字重）
![圖片](https://user-images.githubusercontent.com/8295915/198924182-181dca6d-b784-4563-93b0-9c46ee238a0b.png)
2. 完全正常
3. 中文部分正常，大小正常
![圖片](https://user-images.githubusercontent.com/8295915/198924423-01f6f550-fa73-4d5e-bcb3-c94063c977aa.png)
4. 被點陣化，其餘正常

### 測試 OTF 檔案
1. 效果正常，但檔案很大（15MB）
2. 出現以下錯誤
```
%%[ ProductName: Distiller ]%%
%%[ Error: undefinedresource; OffendingCommand: findresource ]%%

Stack:
/CIDFont
/ChironHeiHKSP-Light
{--pop-- 4 --index-- --add--}
/ChironHeiHKSP-Light-hf
/WinCharSetFFFF-H
/ChironHeiHKSP-LightH


%%[ Flushing: rest of job (to end-of-file) will be ignored ]%%
%%[ Warning: PostScript error. No PDF file produced. ] %%
```
3. 完全正常
4. 被點陣化

### 記事本（使用非測試字體）
1. 全部亂碼，且檔案很大
2. 完全正常
![圖片](https://user-images.githubusercontent.com/8295915/198925209-6dc11923-df94-48e7-bc89-739b3a74b0e9.png)

謝謝！如有需要可以提供輸出的PDF檔案，如需進行更多測試也請儘管提出！也感謝閣下對香港字體的貢獻！

**Comment by tamcy** [comment]
非常感謝協助測試！

我再次更新了 https://github.com/chiron-fonts/chiron-hei-hk-bughunt 中的字型，這次做了一些調整後，上載了兩款黑體、兩款宋體的修正版（字重隨意）。又要麻煩閣下協助測試一下。

首先可以肯定的是 Microsoft Office 的 Export to PDF 功能[並不支援 .otf 格式（準確點說是 OpenType CFF 格式）字型檔](https://support.activepdf.com/support/solutions/articles/35000174189-using-export-for-converting-microsoft-files-that-include-opentype-cff-fonts)。Microsoft 的 PDF Printer 同樣[不支援 OpenType CFF 格式字型](https://community.adobe.com/t5/acrobat-discussions/windows-10-print-to-pdf-error-findfont-courier/m-p/12142429)。這是產品根本問題（像 Export to PDF 不支援 OTF 已持續很多年，Microsoft 看來無意解決），無法以調整字型解決，除非將字型轉為 .TTF 格式。所以，要使用這兩個方法匯出 PDF 文件，唯一辦法就是安裝 .TTF 版本字型檔。（網上有人指用 Mac 版 Office 則無問題，這我有時間會試試，不過這不是重點）。

因此現在的焦點是希望解決 Adobe 的 PDF Maker 和 Print to PDF 所遇到的問題。對於 Adobe 的 PDF Maker，我仍傾向相信是 PDF Maker 本身問題，不過這個問題應可通過調整字型資料避開。現在上傳的測試字型正是朝着這一目標出發。所以，這次又要麻煩閣下幫忙試試以下情況：

1. 字型通過 PDF Maker 輸出的情況。
2. 字型通過列印到 Adobe 的 PDF Printer 輸出的情況。如有錯誤彈出，請[試用本連結方法](https://helpx.adobe.com/acrobat/kb/error--when-you-create-a-postscript-file-you-must-rely-on-system.html)，即在 Adobe PDF 印表機的「內容」頁面中，**不要勾選** *Rely on system fonts only; do not use document fonts* 後再試一次。

（Microsoft 那兩個 PDF Export 就不用了）

感激不盡！

**Comment by fei0316** [comment]
您好， 剛剛測試完畢。使用你提供的四個字體檔案在 Word 輸入中英混合文字並使用 Acrobat 的兩個匯出方法都能正確匯出，文字顯示、檔案大小、選擇文字等都沒有任何問題，就算勾選了 `Rely on system fonts only; do not use document fonts` 亦沒有上次的錯誤。

**Comment by tamcy** [comment]
再次感謝協助測試！有關問題在最新版昭源黑體 (2.505) 及宋體 (1.007) 已經修正。
