### ISSUE TITLE
數字寬度

### ISSUE THREAD

**Issue by Sinacs** [chiron-fonts/chiron-hei-hk#8]
- 數字`4`, `6`, `8`好像太寬;
- 數字`1`有點太窄, 當 `20` 和 `21` 對比起來感覺差距有點大。

不知道這算不算是bug，只是感覺數字寬度稍調整會更好看，感謝！

![Screenshot 2022-10-28 035130](https://user-images.githubusercontent.com/110529913/198385406-8c5cb4c6-dc94-43ae-a26f-bb5159282943.png)

**Comment by tamcy** [comment]
你好！閣下所示圖樣，當中數字並非昭源黑體。昭源黑體之數字式樣當如下圖，各字寬度相同：

![chirondigits](https://user-images.githubusercontent.com/959433/198478142-c2dd76c2-4f5e-48fa-965a-aaf892346939.png)

**Comment by Sinacs** [comment]
抱歉，感謝糾正！
