### ISSUE TITLE
Note: Incorrect glyph component for uni97E5-HK 韥

### ISSUE THREAD

**Issue by NightFurySL2001** [chiron-fonts/chiron-hei-hk#9]
The left side of CID+43917, uni97E5-HK (韥) shows 革 (U+97C7 韇), which should have been 韋. This is an upstream issue.

![image](https://user-images.githubusercontent.com/33471049/200175693-3b2e8f25-b7e6-4b43-8f64-c2d0573fc7ca.png)

Ref: https://github.com/adobe-fonts/source-han-sans/issues/363

**Comment by tamcy** [comment]
Thank you. The glyph has been fixed in the latest release of Chiron Hei HK. BTW, I am aware of your port in the upstream as I have already subscribed to all activities happening on the Source Han Sans/Serif repositories. So there is no need for you to report it here again.

**Comment by NightFurySL2001** [comment]
Thank you. I was just using the font and remembered the issue, and just want to do a report just in case. I'll note it next time.
